import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className + "w-full min-h-screen"}>
          <Nav />
          <main className="max-w-2xl m-auto pt-10 flex flex-col items-center ring-1">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
